import type { SkillCategory, SkillDef } from '../types'

export const SKILL_CATEGORIES: Record<SkillCategory, string> = {
  analysis: 'تحليل ونمو',
  content: 'محتوى وكتابة',
  sales: 'عروض ومبيعات',
  ads: 'إعلانات وسوشال',
  retention: 'عملاء وولاء',
  seasonal: 'مواسم وحملات',
}

const SEASONS = ['رمضان', 'عيد الفطر', 'عيد الأضحى', 'اليوم الوطني السعودي', 'يوم التأسيس', 'الجمعة البيضاء', 'العودة للمدارس', 'موسم الصيف', 'نهاية السنة']
const AD_PLATFORMS = ['سناب شات', 'تيك توك', 'إنستقرام', 'X (تويتر)', 'قوقل', 'كل المنصات']

// كل بطاقة تجمع مهارة أو أكثر من marketingskills وتربطها ببيانات متجر سلة
export const SKILLS: SkillDef[] = [
  {
    slug: 'store-audit',
    title: 'تحليل المتجر الشامل',
    tagline: 'وين أنت الحين، ووين الفرص؟',
    description: 'قراءة كاملة لمتجرك: المبيعات والمنتجات والسلات المتروكة والتقييمات، مع أهم ١٠ فرص نمو مرتبة حسب الأثر.',
    icon: 'ScanSearch',
    tone: 'violet',
    category: 'analysis',
    sources: ['product-marketing', 'cro', 'marketing-ideas'],
    data: ['store', 'products', 'orders', 'customers', 'carts', 'reviews'],
    inputs: [{ key: 'goal', label: 'وش هدفك الأساسي الفترة الجاية؟', type: 'text', placeholder: 'مثال: أرفع المبيعات ٣٠٪ قبل رمضان' }],
    task: `حلّل المتجر تحليلًا تسويقيًا شاملًا. ابدأ بملخص تنفيذي من ٣ أسطر، ثم:
1. لقطة الأداء (أرقام آخر ٣٠ يوم ومتوسط السلة وأكثر المنتجات مبيعًا).
2. نقاط القوة ونقاط الضعف المبنية على البيانات.
3. أهم ١٠ فرص نمو في جدول: الفرصة | لماذا (من البيانات) | الأثر المتوقع | الجهد | أول خطوة.
4. خطة أسبوعين عملية.`,
  },
  {
    slug: 'product-copy',
    title: 'كاتب أوصاف المنتجات',
    tagline: 'أوصاف تبيع، مو بس توصف',
    description: 'يعيد كتابة أوصاف منتجاتك بأسلوب إقناعي ومحسّن لمحركات البحث، ويقدر يطبّقها على متجرك مباشرة.',
    icon: 'PenLine',
    tone: 'teal',
    category: 'content',
    sources: ['copywriting', 'copy-editing', 'marketing-psychology'],
    data: ['store', 'products', 'reviews'],
    inputs: [
      { key: 'tone', label: 'أسلوب الكتابة', type: 'select', options: ['فخم وراقي', 'ودّي وقريب', 'حماسي وشبابي', 'رسمي ومختصر'] },
      { key: 'notes', label: 'ملاحظات إضافية', type: 'textarea', placeholder: 'مثال: ركّز على أن منتجاتنا صناعة سعودية' },
    ],
    task: `راجع أوصاف المنتجات الحالية وقيّم كل وصف باختصار (نقاط الضعف). ثم اكتب وصفًا جديدًا لأهم ٥ منتجات (حسب المبيعات أو الأضعف وصفًا) يشمل: عنوان جذاب، فقرة افتتاحية، ٣-٥ مزايا بصيغة فائدة للعميل، ومعالجة لاعتراض شائع، ودعوة للشراء. في النهاية اذكر أن التاجر يقدر يطبّق الأوصاف من صفحة "المنتجات".`,
  },
  {
    slug: 'abandoned-carts',
    title: 'استرجاع السلات المتروكة',
    tagline: 'رجّع الفلوس اللي وقفت عند الدفع',
    description: 'يحلل السلات المتروكة وأسبابها المحتملة، ويكتب لك تسلسل رسائل استرجاع وعرض مناسب لكل شريحة.',
    icon: 'ShoppingCart',
    tone: 'amber',
    category: 'sales',
    sources: ['churn-prevention', 'emails', 'sms', 'offers'],
    data: ['store', 'carts', 'products', 'orders'],
    inputs: [{ key: 'maxDiscount', label: 'أقصى خصم تقبل تعطيه', type: 'text', placeholder: 'مثال: ١٠٪ أو شحن مجاني' }],
    task: `حلّل السلات المتروكة: قيمتها الإجمالية، المنتجات الأكثر تركًا، أنماط القيمة. اقترح أسبابًا محتملة وحلولًا في صفحة الدفع. ثم اكتب تسلسل استرجاع من ٣ رسائل (بعد ساعة، ٢٤ ساعة، ٧٢ ساعة) لكل من SMS والإيميل، مع العرض المناسب لكل رسالة دون تجاوز الحد الأقصى للخصم. قسّم السلات لشرائح حسب القيمة واقترح معاملة مختلفة لكل شريحة.`,
  },
  {
    slug: 'offers',
    title: 'مهندس العروض',
    tagline: 'عروض ترفع السلة بدون ما تحرق الهامش',
    description: 'يقترح باقات وكوبونات وعروض "اشترِ واحصل" مبنية على أكثر المنتجات مبيعًا ومتوسط السلة.',
    icon: 'BadgePercent',
    tone: 'rose',
    category: 'sales',
    sources: ['offers', 'pricing', 'marketing-psychology'],
    data: ['store', 'products', 'orders', 'coupons'],
    inputs: [{ key: 'margin', label: 'متوسط هامش الربح التقريبي', type: 'text', placeholder: 'مثال: ٤٠٪' }],
    task: `صمّم ٥ عروض قابلة للتنفيذ في سلة (كوبون نسبة، كوبون مبلغ، شحن مجاني فوق حد معين، باقة منتجات، عرض كمية). لكل عرض: الاسم التسويقي، الآلية بالتفصيل، المنتجات المشمولة، الحد الأدنى للسلة المقترح بناءً على متوسط السلة الحالي، الأثر المتوقع، والمخاطر على الهامش. اقترح كود كوبون لكل عرض مناسب. في النهاية اذكر أن التاجر يقدر يطلب من "مساعد رواج" إنشاء الكوبونات مباشرة.`,
  },
  {
    slug: 'ads',
    title: 'نصوص الإعلانات',
    tagline: 'إعلانات جاهزة للنشر',
    description: 'يكتب إعلانات لكل منصة بزوايا مختلفة، مع اقتراحات الاستهداف والصور والفيديو.',
    icon: 'Megaphone',
    tone: 'orange',
    category: 'ads',
    sources: ['ads', 'ad-creative'],
    data: ['store', 'products', 'orders', 'reviews'],
    inputs: [
      { key: 'platform', label: 'المنصة', type: 'select', options: AD_PLATFORMS, required: true },
      { key: 'budget', label: 'الميزانية الشهرية التقريبية', type: 'text', placeholder: 'مثال: ٣٠٠٠ ريال' },
      { key: 'product', label: 'منتج معين؟ (اختياري)', type: 'text', placeholder: 'اتركه فاضي لأفضل المنتجات' },
    ],
    task: `اكتب حملة إعلانية للمنصة المختارة: ٣ زوايا إبداعية مختلفة (مشكلة/حل، دليل اجتماعي من التقييمات، عرض محدود). لكل زاوية: ٣ نسخ نصية بالطول المناسب للمنصة، فكرة التصميم أو سيناريو فيديو قصير (٣ مشاهد)، ودعوة للإجراء. ثم اقترح الاستهداف في السعودية (المدن من بيانات الطلبات، الاهتمامات، الأعمار)، وتوزيع الميزانية، ومؤشرات القياس.`,
  },
  {
    slug: 'social',
    title: 'خطة محتوى السوشال',
    tagline: 'محتوى شهر كامل في دقيقة',
    description: 'تقويم محتوى جاهز بالأفكار والنصوص والهاشتاقات لمنصاتك.',
    icon: 'CalendarDays',
    tone: 'sky',
    category: 'ads',
    sources: ['social', 'content-strategy', 'video'],
    data: ['store', 'products', 'reviews'],
    inputs: [
      { key: 'platform', label: 'المنصة', type: 'select', options: ['إنستقرام', 'تيك توك', 'سناب شات', 'X (تويتر)', 'كل المنصات'] },
      { key: 'period', label: 'المدة', type: 'select', options: ['أسبوعين', 'شهر'] },
    ],
    task: `أنشئ تقويم محتوى للمدة المختارة في جدول: اليوم | نوع المحتوى | الفكرة | النص المقترح | الهاشتاقات. نوّع بين تعليمي وترفيهي وبيعي ودليل اجتماعي (70/20/10 تقريبًا). أضف ٥ أفكار ريلز/تيك توك بسيناريو مختصر، وأفضل أوقات النشر للجمهور السعودي.`,
  },
  {
    slug: 'seo',
    title: 'تدقيق SEO للمتجر',
    tagline: 'خلّ قوقل والذكاء الاصطناعي يلقونك',
    description: 'يراجع عناوين وأوصاف المنتجات وبيانات الميتا، ويقترح كلمات مفتاحية وتحسينات للظهور في قوقل ومحركات الذكاء الاصطناعي.',
    icon: 'Search',
    tone: 'emerald',
    category: 'content',
    sources: ['seo-audit', 'ai-seo', 'schema'],
    data: ['store', 'products'],
    inputs: [],
    task: `دقّق SEO المتجر بناءً على بيانات المنتجات: جودة العناوين، طول ووضوح الأوصاف، وجود عنوان ووصف SEO. اقترح ٢٠ كلمة مفتاحية عربية مناسبة للسوق السعودي مصنفة حسب النية. اكتب عنوان SEO (≤ ٦٠ حرف) ووصف ميتا (≤ ١٥٥ حرف) لكل منتج في جدول. أضف توصيات للظهور في إجابات محركات الذكاء الاصطناعي، وأفكار ٥ مقالات للمدونة.`,
  },
  {
    slug: 'seasonal',
    title: 'حملات المواسم',
    tagline: 'جهّز للموسم قبل المنافسين',
    description: 'خطة حملة كاملة لموسم محدد: العرض، الجدول الزمني، الرسائل، والمحتوى.',
    icon: 'Sparkles',
    tone: 'indigo',
    category: 'seasonal',
    sources: ['launch', 'events', 'marketing-plan', 'offers'],
    data: ['store', 'products', 'orders'],
    inputs: [
      { key: 'season', label: 'الموسم', type: 'select', options: SEASONS, required: true },
      { key: 'budget', label: 'الميزانية التقريبية', type: 'text', placeholder: 'اختياري' },
    ],
    task: `صمّم حملة كاملة للموسم المختار تراعي ثقافة وعادات السعودية فيه: فكرة الحملة الكبيرة واسمها، العرض الرئيسي والمنتجات، جدول زمني (قبل/أثناء/بعد) بالأيام، رسائل SMS والإيميل، أفكار محتوى وإعلانات، وتجهيزات المتجر (بنر، باقات، شحن). اختم بقائمة تحقق للتنفيذ.`,
  },
  {
    slug: 'reviews',
    title: 'تحليل آراء العملاء',
    tagline: 'وش يقولون عنك فعلًا؟',
    description: 'يلخص التقييمات إلى مواضيع ومشاعر، ويستخرج منها رسائل تسويقية وتحسينات للمنتجات.',
    icon: 'MessageSquareHeart',
    tone: 'rose',
    category: 'retention',
    sources: ['customer-research', 'copywriting'],
    data: ['store', 'reviews', 'products'],
    inputs: [],
    task: `حلّل التقييمات: التوزيع، أبرز المواضيع الإيجابية والسلبية مع اقتباسات، والمنتجات الأعلى والأدنى رضًا. استخرج "لغة العميل" (عبارات يستخدمها العملاء) وحوّلها إلى ٥ عناوين تسويقية. اكتب ردودًا مقترحة على التقييمات السلبية، وقائمة تحسينات تشغيلية.`,
  },
  {
    slug: 'customers',
    title: 'شرائح العملاء والولاء',
    tagline: 'اعرف عملاءك ورجّعهم',
    description: 'يقسّم عملاءك لشرائح (VIP، جدد، خاملين…) ويقترح برنامج ولاء وإحالة ورسائل لكل شريحة.',
    icon: 'Users',
    tone: 'sky',
    category: 'retention',
    sources: ['churn-prevention', 'referrals', 'customer-research'],
    data: ['store', 'customers', 'orders'],
    inputs: [],
    task: `قسّم العملاء إلى شرائح بمنطق RFM مبسط باستخدام البيانات المتاحة (عدد الطلبات، المبلغ، المدن). لكل شريحة: الحجم، الخصائص، الهدف، والرسالة والعرض المناسب. صمّم برنامج إحالة بسيط قابل للتنفيذ في سلة، وحملة لإعادة تنشيط العملاء الخاملين.`,
  },
  {
    slug: 'messages',
    title: 'رسائل SMS والإيميل',
    tagline: 'رسائل قصيرة تجيب نتيجة',
    description: 'يكتب رسائل ترحيب وإعادة شراء وعروض بصيغة SMS وإيميل جاهزة.',
    icon: 'Mail',
    tone: 'teal',
    category: 'retention',
    sources: ['emails', 'sms'],
    data: ['store', 'products', 'orders'],
    inputs: [{ key: 'goal', label: 'هدف الرسائل', type: 'select', options: ['ترحيب بعميل جديد', 'إعادة شراء', 'إطلاق منتج جديد', 'عرض محدود', 'طلب تقييم'], required: true }],
    task: `اكتب تسلسلًا من ٣-٤ رسائل للهدف المختار. لكل رسالة: التوقيت، نسخة SMS (≤ ١٦٠ حرفًا مع الرابط)، ونسخة إيميل (عنوان + نص معاينة + المحتوى + زر). استخدم أسماء منتجات حقيقية من المتجر.`,
  },
  {
    slug: 'influencers',
    title: 'حملة المشاهير والمؤثرين',
    tagline: 'مؤثر مناسب بميزانية منطقية',
    description: 'خطة تعاون مع المؤثرين: نوع المؤثر المناسب، الرسالة، البريف، وطريقة القياس.',
    icon: 'Star',
    tone: 'amber',
    category: 'ads',
    sources: ['influencer-marketing'],
    data: ['store', 'products', 'orders'],
    inputs: [{ key: 'budget', label: 'الميزانية', type: 'text', placeholder: 'مثال: ١٠٬٠٠٠ ريال', required: true }],
    task: `ضع خطة حملة مؤثرين في السعودية ضمن الميزانية: فئة المؤثرين (نانو/مايكرو/ماكرو) وعددهم وتوزيع الميزانية، معايير الاختيار، بريف جاهز للإرسال، ٣ أفكار محتوى، كود خصم لكل مؤثر للقياس، ومؤشرات النجاح. نبّه على متطلبات الإفصاح الإعلاني وترخيص موثوق.`,
  },
  {
    slug: 'marketing-plan',
    title: 'خطة تسويق ٩٠ يوم',
    tagline: 'خارطة طريق واضحة',
    description: 'خطة تسويق ربع سنوية بالأولويات والقنوات والميزانية والمؤشرات.',
    icon: 'Map',
    tone: 'indigo',
    category: 'analysis',
    sources: ['marketing-plan', 'marketing-ideas', 'product-marketing'],
    data: ['store', 'products', 'orders', 'customers'],
    inputs: [
      { key: 'goal', label: 'الهدف', type: 'text', placeholder: 'مثال: ٥٠٠ طلب شهريًا', required: true },
      { key: 'budget', label: 'الميزانية الشهرية', type: 'text' },
    ],
    task: `ضع خطة تسويق لـ ٩٠ يومًا: التموضع والرسالة الأساسية، الجمهور المستهدف، القنوات بالأولوية، خطة شهرية (شهر ١، ٢، ٣) بمهام أسبوعية، توزيع الميزانية، ومؤشرات أداء بأرقام مستهدفة مبنية على الأداء الحالي.`,
  },
  {
    slug: 'conversion',
    title: 'رفع معدل التحويل',
    tagline: 'زوار أكثر يصيرون مشترين',
    description: 'توصيات لصفحات المنتج والسلة والنوافذ المنبثقة لرفع التحويل، مع أفكار اختبارات A/B.',
    icon: 'TrendingUp',
    tone: 'emerald',
    category: 'sales',
    sources: ['cro', 'popups', 'marketing-psychology'],
    data: ['store', 'products', 'orders', 'carts', 'reviews'],
    inputs: [],
    task: `اقترح تحسينات تحويل مرتبة بالأولوية لـ: الصفحة الرئيسية، صفحة المنتج، السلة والدفع. صمّم نافذتين منبثقتين (النص والتوقيت والعرض). اقترح ٥ اختبارات A/B بفرضية واضحة ومقياس نجاح. استفد من السلات المتروكة والتقييمات كدليل.`,
  },
]

export function getSkill(slug: string): SkillDef | undefined {
  return SKILLS.find(s => s.slug === slug)
}
